name: Build Containers Only

on:
  workflow_dispatch:
    inputs:
      target_os:
        description: 'Target OS'
        required: true
        default: 'rocky8'
        type: choice
        options:
        - rocky8
        - rocky9
        - both
      push_to_registry:
        description: 'Push to registry'
        required: false
        default: true
        type: boolean
      run_tests:
        description: 'Run tests'
        required: false
        default: true
        type: boolean

env:
  SPACK_ROOT: "/opt/spack"
  SPACK_ENVIRONMENT: "skipper"
  APPTAINER_VERSION: "1.2.5"
  CONTAINER_REGISTRY: "ghcr.io"

jobs:
  build-rocky8:
    name: Build Rocky 8 Container
    runs-on: ubuntu-latest
    timeout-minutes: 240
    if: github.event.inputs.target_os == 'rocky8' || github.event.inputs.target_os == 'both'
    
    permissions:
      contents: read
      packages: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Apptainer
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://github.com/apptainer/apptainer/releases/download/v${{ env.APPTAINER_VERSION }}/apptainer_${{ env.APPTAINER_VERSION }}_amd64.deb
        sudo apt-get install -y ./apptainer_${{ env.APPTAINER_VERSION }}_amd64.deb

    - name: Build Rocky 8 container
      run: |
        echo "Building Rocky Linux 8 Apptainer container..."
        cd containers
        sudo apptainer build \
          --fakeroot \
          --tmpdir /tmp \
          hpc-spack-skipper-rocky8.sif \
          rocky8/skipper-rocky8.def

    - name: Test container
      if: github.event.inputs.run_tests == 'true'
      run: |
        echo "Testing Rocky 8 container..."
        cd containers
        apptainer test hpc-spack-skipper-rocky8.sif

    - name: Log in to GitHub Container Registry
      if: github.event.inputs.push_to_registry == 'true'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Convert and push to registry
      if: github.event.inputs.push_to_registry == 'true'
      run: |
        cd containers
        docker import hpc-spack-skipper-rocky8.sif ghcr.io/${{ github.repository_owner }}/hpc-spack-rocky8:manual-${{ github.run_number }}
        docker push ghcr.io/${{ github.repository_owner }}/hpc-spack-rocky8:manual-${{ github.run_number }}

    - name: Upload container artifact
      uses: actions/upload-artifact@v4
      with:
        name: hpc-spack-rocky8-container
        path: containers/hpc-spack-skipper-rocky8.sif
        retention-days: 30

  build-rocky9:
    name: Build Rocky 9 Container
    runs-on: ubuntu-latest
    timeout-minutes: 240
    if: github.event.inputs.target_os == 'rocky9' || github.event.inputs.target_os == 'both'
    
    permissions:
      contents: read
      packages: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Apptainer
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://github.com/apptainer/apptainer/releases/download/v${{ env.APPTAINER_VERSION }}/apptainer_${{ env.APPTAINER_VERSION }}_amd64.deb
        sudo apt-get install -y ./apptainer_${{ env.APPTAINER_VERSION }}_amd64.deb

    - name: Build Rocky 9 container
      run: |
        echo "Building Rocky Linux 9 Apptainer container..."
        cd containers
        sudo apptainer build \
          --fakeroot \
          --tmpdir /tmp \
          hpc-spack-skipper-rocky9.sif \
          rocky9/skipper-rocky9.def

    - name: Test container
      if: github.event.inputs.run_tests == 'true'
      run: |
        echo "Testing Rocky 9 container..."
        cd containers
        apptainer test hpc-spack-skipper-rocky9.sif

    - name: Log in to GitHub Container Registry
      if: github.event.inputs.push_to_registry == 'true'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Convert and push to registry
      if: github.event.inputs.push_to_registry == 'true'
      run: |
        cd containers
        docker import hpc-spack-skipper-rocky9.sif ghcr.io/${{ github.repository_owner }}/hpc-spack-rocky9:manual-${{ github.run_number }}
        docker push ghcr.io/${{ github.repository_owner }}/hpc-spack-rocky9:manual-${{ github.run_number }}

    - name: Upload container artifact
      uses: actions/upload-artifact@v4
      with:
        name: hpc-spack-rocky9-container
        path: containers/hpc-spack-skipper-rocky9.sif
        retention-days: 30
